package com.shopping.dessert.exceptionHandler;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@AllArgsConstructor
@Getter
public enum ErrorCode {
    NOT_FOUND(404,"COMMON_ERROR_404","PAGE NOT FOUND"),
    SERVER_ERROR(500,"COMMON_ERROR_500","SERVER ERROR"),

    // USER
    EMAIL_DUPLICATION(1000,"USER_ERROR_1000","EMAIL DUPLICATED"),
    PASSWORD_INVALID(1001,"USER_ERROR_1001","PASSWORD INVALID"),
    USER_NOT_FOUND(1002,"USER_ERROR_1002","USER NOT FOUND"),
    WRITER_NOT_MATCH(1003, "USER_ERROR_1003","WRITER_NOT_MATCH"),

    // NOT FOUND
    PRODUCT_NOT_FOUND(2000,"PRODUCT_ERROR_2000","PRODUCT NOT FOUND"),
    POST_NOT_FOUND(2001,"POST_ERROR_2001","POST NOT FOUND"),
    ORDER_NOT_FOUND(2002,"ORDER_ERROR_2002","ORDER NOT FOUND"),
    CART_NOT_FOUND(2003,"CART_ERROR_2003","CART NOT FOUND"),
    REPLY_NOT_FOUND(2004,"REPLY_ERROR_2004","REPLY NOT FOUND"),


    ;

    private int status;
    private String errorCode;
    private String message;

}
