

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dessert?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  thymeleaf:
    cache: false
  data:
    web:
      pageable:
        default-page-size: 3
        max-page-size: 2000

server:
  port: 8080


