

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dessert?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    suffix: .html

server:
  port: 8080